Introduce monitoring
osiam/osiam pull request #265
Opened 2016-10-09 22:45 UTC by dacrome

- Add /monitor endpoint which groups a lot of endpoints [1] which
provide monitoring information about the running OSIAM app
- Extends response of /monitor/info to provide java version and encoding
- Create short documentation
- Remove old /Metrics endpoint and dependencies

[1] http://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/html/production-ready-endpoints.html

Resolves #8

2016-10-10 10:57 UTC, dacrome commented on src/main/resources/application.yml
> +management.context-path: /monitor
I'm not really happy with this path. Some more ideas: `/admin`, `/manage`, `/management` and `/monitoring`. Any other?

2016-10-25 18:55 UTC, tkrille commented on src/main/resources/application.yml
> +management.context-path: /monitor
It's more than monitoring, that's right. I would say `/manage` or `/management`. Take your pick! :)

2016-10-25 19:07 UTC, tkrille requested changes

2016-10-25 19:07 UTC, tkrille commented on CHANGELOG.md
> +## 3.1 - 201x-xx-xx
It's either "Unreleased" or no version at all. But "201x-xx-xx" looks kinda weird :)

2016-10-25 19:07 UTC, tkrille commented on src/main/resources/application.yml
> +    target: @java.version@
I don't think we need to expose this kind of information. [This](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-application-info-build) looks far more interesting. But it's better to add it, after the Gradle migration is done.

2016-10-25 19:09 UTC, tkrille commented
Doesn't that break the ITs?

2016-10-25 19:20 UTC, tkrille commented
Indeed it does:

```
can_access_metrics_endpoint(org.osiam.client.AdminScopeIT)  Time elapsed: 0.893 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <200>
     but: was <404>
```

2016-10-25 19:27 UTC, dacrome commented on CHANGELOG.md
> +## 3.1 - 201x-xx-xx
Okay

2016-10-25 19:28 UTC, dacrome commented on src/main/resources/application.yml
> +management.context-path: /monitor
`management`

2016-10-25 19:28 UTC, dacrome commented on src/main/resources/application.yml
> +    target: @java.version@
Okay

2016-10-25 19:29 UTC, dacrome commented
Ups, sorry. I will update the ITs.

2016-10-25 19:36 UTC, tkrille commented on src/main/resources/application.yml
> +management.context-path: /monitor
:+1:

2016-10-25 22:05 UTC, wallner commented on src/main/resources/application.yml
> +management.context-path: /monitor
management is fine.

2016-10-26 18:48 UTC, tkrille approved these changes

2016-10-26 18:48 UTC, merged